gpu_list:
    - 5
seed: null
dump_path: './outputs/'
defaults:
    - data: iwcd
    - model: resnet18
    - engine: classifier
    - tasks/train: train_resnet
    - tasks/restore_best_state: restore_best_state
    - tasks/evaluate: test
    - _self_
