defaults:
    - data/dataset: tutorial_data
    - model: resnet18
    - tasks/train: train_resnet
    - tasks/restore_best_state: restore_best_state
    - tasks/evaluate: test
tasks:
  train:
    epochs: 5
gpu_list: [] # train on CPU
seed: null
dump_path: './outputs/'
